Feat/before swap
Uniswap-Hook-Incubation-1st-Cohort-2024/am-amm pull request #4
Opened 2024-06-04 11:00 UTC by leckylao

2024-06-05 23:03 UTC, ChinmayGopal931 requested changes

2024-06-05 23:03 UTC, ChinmayGopal931 commented on test/AmAmmHook.t.sol
> +        (key, ) = initPoolAndAddLiquidity(
This test is using the incorrect Pool. see #5 for solution.

2024-06-05 23:03 UTC, ChinmayGopal931 commented on src/AMAMMHOOK.sol
> +        poolManager.take(bidToken, address(AMAMM), rent);
Rent should not be transferred back to amAmm. I should be left for Lps

2024-06-09 02:56 UTC, 0xidli approved these changes

2024-06-09 02:56 UTC, ChinmayGopal931 approved these changes

2024-06-09 05:55 UTC, merged